# Generated by Django 5.0.2 on 2026-04-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0015_add_unique_content_hash'),
        ('feeds', '0003_language_description_region_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField(max_length=1024, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('last_modified', models.CharField(blank=True, max_length=255)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('consecutive_errors', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True)),
                ('feed_type', models.CharField(blank=True, max_length=20)),
                ('feed_description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss_feeds', to='feeds.language')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_feeds', to='feeds.publication')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss_feeds', to='feeds.region')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss_feeds', to='feeds.topic')),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
                'ordering': ['priority', 'publication__name'],
            },
        ),
        migrations.CreateModel(
            name='RSSFeedSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_created', models.IntegerField(default=0)),
                ('articles_updated', models.IntegerField(default=0)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('was_modified', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='rssfeeds.rssfeed')),
            ],
            options={
                'verbose_name': 'RSS Feed Sync Log',
                'verbose_name_plural': 'RSS Feed Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RSSArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, db_index=True, max_length=1024)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rss_data', to='articles.article')),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='rssfeeds.rssfeed')),
                ('sync_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='rssfeeds.rssfeedsynclog')),
            ],
            options={
                'verbose_name': 'RSS Article',
                'verbose_name_plural': 'RSS Articles',
            },
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['status'], name='rssfeeds_rs_status_844f28_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['last_fetched_at'], name='rssfeeds_rs_last_fe_05928e_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['priority'], name='rssfeeds_rs_priorit_bb74f9_idx'),
        ),
        migrations.AddIndex(
            model_name='rssarticle',
            index=models.Index(fields=['guid'], name='rssfeeds_rs_guid_51337d_idx'),
        ),
        migrations.AddIndex(
            model_name='rssarticle',
            index=models.Index(fields=['fetched_at'], name='rssfeeds_rs_fetched_2dea05_idx'),
        ),
    ]
