FROM node:18-alpine

WORKDIR /app

# Install essential development tools
RUN apk add --no-cache bash git curl

# Make entrypoint script executable
COPY docker-entrypoint.dev.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Expose port
EXPOSE 3000

# Set environment variables
ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1
ENV HOST 0.0.0.0

# Set the entrypoint script
ENTRYPOINT ["docker-entrypoint.sh"]

# Start development server
CMD ["npm", "run", "dev"] 