# Generated by Django 5.0.2 on 2025-06-18 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_remove_articleevent_analyzer_article_event_is_primary_idx_and_more'),
        ('articles', '0015_add_unique_content_hash'),
        ('digest', '0001_initial'),
        ('feeds', '0003_language_description_region_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_abstract', models.TextField(help_text='AI-generated topic summary (2-3 sentences)')),
                ('main_facts', models.JSONField(default=list, help_text='Top 5 facts across all events in this topic (list of strings)')),
                ('perspectives', models.JSONField(default=list, help_text='Key perspectives/opinions from different sources (list of strings)')),
                ('order', models.IntegerField(default=0, help_text='Display order within the digest')),
                ('event_count', models.IntegerField(default=0, help_text='Number of events in this topic section')),
                ('article_count', models.IntegerField(default=0, help_text='Total articles contributing to this topic')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate this topic summary', max_digits=6)),
                ('tokens_input', models.IntegerField(default=0, help_text='Input tokens for this topic generation')),
                ('tokens_output', models.IntegerField(default=0, help_text='Output tokens for this topic generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Digest topics',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='digeststory',
            options={'ordering': ['digest_topic__order', 'order'], 'verbose_name_plural': 'Digest stories'},
        ),
        migrations.AddField(
            model_name='digest',
            name='ai_model_used',
            field=models.CharField(blank=True, help_text='AI model used for content generation', max_length=50),
        ),
        migrations.AddField(
            model_name='digest',
            name='articles_processed',
            field=models.IntegerField(default=0, help_text='Number of articles processed for this digest'),
        ),
        migrations.AddField(
            model_name='digest',
            name='digest_preferences',
            field=models.JSONField(default=dict, help_text='User preferences snapshot at generation time'),
        ),
        migrations.AddField(
            model_name='digest',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if generation failed'),
        ),
        migrations.AddField(
            model_name='digest',
            name='events_included',
            field=models.IntegerField(default=0, help_text='Number of events included in this digest'),
        ),
        migrations.AddField(
            model_name='digest',
            name='generation_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Total cost in USD for generating this digest', max_digits=8),
        ),
        migrations.AddField(
            model_name='digest',
            name='generation_duration_ms',
            field=models.IntegerField(default=0, help_text='Time taken to generate digest in milliseconds'),
        ),
        migrations.AddField(
            model_name='digest',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending Generation'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of digest generation', max_length=20),
        ),
        migrations.AddField(
            model_name='digest',
            name='tokens_input',
            field=models.IntegerField(default=0, help_text='Total input tokens used'),
        ),
        migrations.AddField(
            model_name='digest',
            name='tokens_output',
            field=models.IntegerField(default=0, help_text='Total output tokens generated'),
        ),
        migrations.AddField(
            model_name='digest',
            name='topics_included',
            field=models.IntegerField(default=0, help_text='Number of topics included in this digest'),
        ),
        migrations.AddField(
            model_name='digest',
            name='user_timezone',
            field=models.CharField(default='UTC', help_text="User's timezone when digest was generated", max_length=50),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='article_count',
            field=models.IntegerField(default=0, help_text='Total articles mentioning this event (primary + secondary)'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='enhanced_abstract',
            field=models.TextField(blank=True, help_text='AI-enhanced event summary synthesizing multiple articles'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The primary event this story represents', null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.event'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='event_score',
            field=models.FloatField(default=0.0, help_text='Calculated importance score (primary_count * 2 + secondary_count)'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='generation_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate enhanced content for this story', max_digits=6),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='key_facts',
            field=models.JSONField(default=list, help_text='Key facts from multiple articles about this event (list of strings)'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='perspectives',
            field=models.JSONField(default=list, help_text='Different viewpoints/opinions about this event (list of strings)'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='primary_mentions',
            field=models.IntegerField(default=0, help_text='Articles with this as primary event'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='recommended_articles',
            field=models.ManyToManyField(blank=True, help_text='3 most recent/relevant articles for deep dive reading', related_name='digest_recommendations', to='articles.article'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='secondary_mentions',
            field=models.IntegerField(default=0, help_text='Articles with this as secondary event'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='tokens_input',
            field=models.IntegerField(default=0, help_text='Input tokens for this story generation'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='tokens_output',
            field=models.IntegerField(default=0, help_text='Output tokens for this story generation'),
        ),
        migrations.AlterField(
            model_name='digeststory',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='digest_stories', to='articles.article'),
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['generation_status'], name='digest_dige_generat_da8886_idx'),
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['user', 'date'], name='digest_dige_user_id_9340e3_idx'),
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['user', 'generation_status'], name='digest_dige_user_id_8f7e7a_idx'),
        ),
        migrations.AddField(
            model_name='digesttopic',
            name='digest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_topics', to='digest.digest'),
        ),
        migrations.AddField(
            model_name='digesttopic',
            name='topic',
            field=models.ForeignKey(help_text='The topic this section covers', on_delete=django.db.models.deletion.CASCADE, to='feeds.topic'),
        ),
        migrations.AddField(
            model_name='digeststory',
            name='digest_topic',
            field=models.ForeignKey(blank=True, help_text='The topic section this story belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='digest.digesttopic'),
        ),
        migrations.AddIndex(
            model_name='digeststory',
            index=models.Index(fields=['digest_topic', 'order'], name='digest_dige_digest__073af8_idx'),
        ),
        migrations.AddIndex(
            model_name='digeststory',
            index=models.Index(fields=['event'], name='digest_dige_event_i_d11805_idx'),
        ),
        migrations.AddIndex(
            model_name='digeststory',
            index=models.Index(fields=['event_score'], name='digest_dige_event_s_089745_idx'),
        ),
        migrations.AddIndex(
            model_name='digesttopic',
            index=models.Index(fields=['digest', 'order'], name='digest_dige_digest__3df2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='digesttopic',
            index=models.Index(fields=['topic'], name='digest_dige_topic_i_b8cf6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='digesttopic',
            unique_together={('digest', 'topic')},
        ),
    ]
