# Generated by Django 5.0.2 on 2025-07-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0002_enhance_digest_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='conclusion',
            field=models.TextField(blank=True, help_text="AI-generated conclusion wrapping up the day's stories"),
        ),
    ]
