# Generated by Django 5.0.2 on 2025-07-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0003_add_conclusion_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='headline',
            field=models.CharField(blank=True, help_text='AI-generated compelling headline for the digest', max_length=100),
        ),
    ]
