# Generated by Django 5.0.2 on 2025-07-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0004_add_digest_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='reading_time_minutes',
            field=models.IntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
    ]
