# Generated by Django 5.0.2 on 2025-04-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(help_text='Short abstract of the article (1-3 sentences)')),
                ('key_points', models.TextField(help_text='Key points extracted from the article')),
                ('full_summary', models.TextField(help_text='Full detailed summary of the article')),
                ('is_translated', models.BooleanField(default=False)),
                ('original_language', models.CharField(blank=True, max_length=5)),
                ('ai_provider', models.CharField(blank=True, help_text='Which AI provider generated this summary', max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0, help_text='Time taken to generate the summary in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='SummarizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarization_requests', to='articles.article')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='summariser__status_bce424_idx'), models.Index(fields=['article', 'status'], name='summariser__article_c6b9ab_idx')],
            },
        ),
    ]
