# Generated by Django 5.0.2 on 2025-05-27 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(db_index=True)),
                ('article_url', models.URLField(max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('success', 'Success'), ('failed', 'Failed'), ('paywall', 'Paywall Detected'), ('access_denied', 'Access Denied'), ('timeout', 'Timeout'), ('invalid_url', 'Invalid URL'), ('technical_error', 'Technical Error')], default='pending', max_length=20)),
                ('attempt_number', models.IntegerField(default=1)),
                ('content_source', models.CharField(blank=True, choices=[('full_fetch', 'Full Content Fetched'), ('partial_fetch', 'Partial Content Fetched'), ('description_fallback', 'Using Description as Fallback'), ('no_content', 'No Content Available')], max_length=20, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('content_quality_score', models.FloatField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('user_agent_used', models.CharField(blank=True, max_length=255)),
                ('extraction_strategy', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=50)),
                ('paywall_detected', models.BooleanField(default=False)),
                ('paywall_indicators', models.JSONField(blank=True, default=list)),
                ('extracted_text_length', models.IntegerField(blank=True, null=True)),
                ('has_main_content', models.BooleanField(default=False)),
                ('content_completeness', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Content Fetch Log',
                'verbose_name_plural': 'Content Fetch Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article_id', '-created_at'], name='fetcher_con_article_c0fe4b_idx'), models.Index(fields=['status'], name='fetcher_con_status_ae9bd7_idx'), models.Index(fields=['-created_at'], name='fetcher_con_created_eca09c_idx'), models.Index(fields=['paywall_detected'], name='fetcher_con_paywall_09fd65_idx')],
            },
        ),
        migrations.CreateModel(
            name='FetchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(db_index=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('final_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fetch Attempt Tracker',
                'verbose_name_plural': 'Fetch Attempt Trackers',
                'indexes': [models.Index(fields=['next_retry_at'], name='fetcher_fet_next_re_784855_idx'), models.Index(fields=['is_completed'], name='fetcher_fet_is_comp_d7e7d0_idx')],
                'unique_together': {('article_id',)},
            },
        ),
    ]
