# Generated by Django 5.0.2 on 2025-05-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfetchlog',
            name='content_blocks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentfetchlog',
            name='formatting_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contentfetchlog',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentfetchlog',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentfetchlog',
            name='has_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentfetchlog',
            name='media_assets_count',
            field=models.IntegerField(default=0),
        ),
    ]
