# Generated by Django 5.0.2 on 2025-05-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_add_rich_content_tracking_to_fetch_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentFetchLog',
        ),
        migrations.DeleteModel(
            name='FetchAttempt',
        ),
    ]
