# Generated by Django 5.0.2 on 2025-06-16 20:02

import django.db.models.deletion
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0012_article_last_summarization_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for aggregated metrics', unique=True)),
                ('articles_processed', models.IntegerField(default=0)),
                ('articles_failed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate percentage')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('avg_cost_per_article', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('avg_duration_ms', models.IntegerField(default=0)),
                ('avg_tokens_used', models.IntegerField(default=0)),
                ('new_entities_created', models.IntegerField(default=0)),
                ('entity_deduplication_rate', models.FloatField(default=0.0)),
                ('new_events_created', models.IntegerField(default=0)),
                ('event_clustering_rate', models.FloatField(default=0.0)),
                ('topic_assignment_rate', models.FloatField(default=0.0)),
                ('region_assignment_rate', models.FloatField(default=0.0)),
                ('linguistic_failures', models.IntegerField(default=0)),
                ('entity_failures', models.IntegerField(default=0)),
                ('event_failures', models.IntegerField(default=0)),
                ('topic_failures', models.IntegerField(default=0)),
                ('region_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analyzer_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('canonical_name', models.CharField(help_text='Canonicalized name (lowercase, normalized)', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=255)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization'), ('LOCATION', 'Location'), ('FACILITY', 'Facility'), ('EVENT', 'Event'), ('WORK', 'Creative Work'), ('PRODUCT', 'Product'), ('FINANCIAL_ASSET', 'Financial Asset'), ('LAW', 'Law/Regulation'), ('PROGRAM', 'Program/Policy'), ('OTHER', 'Other')], help_text='Entity type classification', max_length=20)),
                ('wikidata_id', models.CharField(blank=True, max_length=50, null=True)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=384, help_text='384-dimensional vector for semantic similarity', null=True)),
                ('article_count', models.IntegerField(default=0, help_text='Number of articles mentioning this entity')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'db_table': 'analyzer_entity',
                'indexes': [models.Index(fields=['canonical_name'], name='analyzer_en_canonic_b75339_idx'), models.Index(fields=['entity_type'], name='analyzer_en_entity__1f00b3_idx'), models.Index(fields=['article_count'], name='analyzer_en_article_0799ed_idx'), models.Index(fields=['last_seen_at'], name='analyzer_en_last_se_eddea1_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alternative name or spelling', max_length=255, unique=True)),
                ('alias_type', models.CharField(choices=[('abbreviation', 'Abbreviation'), ('acronym', 'Acronym'), ('ticker', 'Stock Ticker'), ('nickname', 'Nickname'), ('spelling', 'Alternative Spelling'), ('translation', 'Translation'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='analyzer.entity')),
            ],
            options={
                'verbose_name_plural': 'Entity aliases',
                'db_table': 'analyzer_entity_alias',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('abstract', models.TextField(help_text='AI-generated event summary')),
                ('facts', models.JSONField(default=list, help_text='Key facts extracted from related articles')),
                ('event_hash', models.CharField(help_text='SHA-256 hash for exact deduplication', max_length=64, unique=True)),
                ('centroid_embed', pgvector.django.VectorField(dimensions=1536, help_text='Centroid embedding for event similarity clustering')),
                ('first_seen_at', models.DateTimeField(help_text='When this event was first detected')),
                ('last_seen_at', models.DateTimeField(help_text='Most recent article about this event')),
                ('article_count', models.IntegerField(default=1, help_text='Number of articles about this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_group', models.OneToOneField(blank=True, help_text='Link to existing story group if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzer_event', to='articles.storygroup')),
            ],
            options={
                'db_table': 'analyzer_event',
            },
        ),
        migrations.CreateModel(
            name='ArticleEvent',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='main_event', serialize=False, to='articles.article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='analyzer.event')),
            ],
            options={
                'db_table': 'analyzer_article_event',
            },
        ),
        migrations.CreateModel(
            name='EventEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1.0, help_text='Relevance of entity to event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_events', to='analyzer.entity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_entities', to='analyzer.event')),
            ],
            options={
                'db_table': 'analyzer_event_entity',
            },
        ),
        migrations.CreateModel(
            name='AnalyzerRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('linguistic_processing', 'Linguistic Processing'), ('entity_processing', 'Entity Processing'), ('event_processing', 'Event Processing'), ('topic_processing', 'Topic Processing'), ('region_processing', 'Region Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=30)),
                ('current_stage', models.CharField(blank=True, max_length=30)),
                ('stages_completed', models.JSONField(default=list)),
                ('pipeline_start_time', models.DateTimeField(blank=True, null=True)),
                ('pipeline_end_time', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('failed_stage', models.CharField(blank=True, max_length=30)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('total_duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_requests', to='articles.article')),
            ],
            options={
                'db_table': 'analyzer_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='analyzer_re_status_d14b0f_idx'), models.Index(fields=['article', 'status'], name='analyzer_re_article_5c4c24_idx'), models.Index(fields=['current_stage'], name='analyzer_re_current_0596d1_idx'), models.Index(fields=['created_at'], name='analyzer_re_created_991849_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('analyzer_version', models.CharField(default='1.0', max_length=10)),
                ('tokens_input', models.IntegerField(default=0, help_text='Total input tokens used')),
                ('tokens_output', models.IntegerField(default=0, help_text='Total output tokens generated')),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Total processing time in milliseconds')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Total cost in USD', max_digits=8)),
                ('ai_model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('language_confidence', models.FloatField(default=0.0, help_text='Confidence score for language detection')),
                ('primary_topic_confidence', models.FloatField(default=0.0, help_text='Confidence score for primary topic classification')),
                ('primary_region_confidence', models.FloatField(default=0.0, help_text='Confidence score for primary region detection')),
                ('style_tone', models.CharField(blank=True, choices=[('factual', 'Factual'), ('opinion', 'Opinion'), ('narrative', 'Narrative'), ('analytical', 'Analytical'), ('satirical', 'Satirical'), ('sensational', 'Sensational')], help_text='Article style and tone classification', max_length=20, null=True)),
                ('readability_flesch', models.FloatField(blank=True, help_text='Flesch readability score (0-100)', null=True)),
                ('reading_time_sec', models.IntegerField(blank=True, help_text='Estimated reading time in seconds', null=True)),
                ('secondary_topics', models.JSONField(default=list, help_text='List of secondary topic slugs')),
                ('secondary_regions', models.JSONField(default=list, help_text='List of secondary region codes')),
                ('stages_completed', models.JSONField(default=list, help_text='List of completed analysis stages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_result', to='articles.article')),
            ],
            options={
                'verbose_name': 'Article Analysis',
                'verbose_name_plural': 'Article Analyses',
                'db_table': 'analyzer_article_analysis',
                'indexes': [models.Index(fields=['article'], name='analyzer_ar_article_92b241_idx'), models.Index(fields=['analyzer_version'], name='analyzer_ar_analyze_60f43e_idx'), models.Index(fields=['created_at'], name='analyzer_ar_created_463e1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score for entity extraction')),
                ('mention_count', models.IntegerField(default=1, help_text='Number of times entity is mentioned in article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_entities', to='articles.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_articles', to='analyzer.entity')),
            ],
            options={
                'db_table': 'analyzer_article_entity',
                'indexes': [models.Index(fields=['article'], name='analyzer_ar_article_c78874_idx'), models.Index(fields=['entity'], name='analyzer_ar_entity__1adb4b_idx'), models.Index(fields=['confidence'], name='analyzer_ar_confide_04497b_idx')],
                'unique_together': {('article', 'entity')},
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_hash'], name='analyzer_ev_event_h_619788_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['last_seen_at'], name='analyzer_ev_last_se_258990_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['article_count'], name='analyzer_ev_article_63bb84_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['first_seen_at'], name='analyzer_ev_first_s_23b76e_idx'),
        ),
        migrations.AddIndex(
            model_name='evententity',
            index=models.Index(fields=['event'], name='analyzer_ev_event_i_d1f606_idx'),
        ),
        migrations.AddIndex(
            model_name='evententity',
            index=models.Index(fields=['entity'], name='analyzer_ev_entity__3350c1_idx'),
        ),
        migrations.AddIndex(
            model_name='evententity',
            index=models.Index(fields=['relevance_score'], name='analyzer_ev_relevan_cd6049_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evententity',
            unique_together={('event', 'entity')},
        ),
    ]
