# Generated by Django 5.0.2 on 2025-06-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleanalysis',
            name='readability_flesch',
        ),
        migrations.RemoveField(
            model_name='articleanalysis',
            name='reading_time_sec',
        ),
    ]
