# Generated by Django 5.0.2 on 2025-06-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_update_entity_embedding_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleanalysis',
            name='primary_region_code',
            field=models.CharField(blank=True, help_text='Code of the primary region', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='articleanalysis',
            name='primary_topic_slug',
            field=models.CharField(blank=True, help_text='Slug of the primary topic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articleanalysis',
            name='region_relevance',
            field=models.JSONField(default=dict, help_text='Region relevance scores as {region_code: score}'),
        ),
        migrations.AddField(
            model_name='articleanalysis',
            name='secondary_region_codes',
            field=models.JSONField(default=list, help_text='List of secondary region codes'),
        ),
        migrations.AddField(
            model_name='articleanalysis',
            name='secondary_topic_slugs',
            field=models.JSONField(default=list, help_text='List of secondary topic slugs'),
        ),
        migrations.AddField(
            model_name='articleanalysis',
            name='topic_relevance',
            field=models.JSONField(default=dict, help_text='Topic relevance scores as {topic_slug: score}'),
        ),
    ]
