# Generated by Django 5.0.2 on 2025-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_merge_20250601_0000'),
        ('articles', '0014_add_readability_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('product_launch', 'Product Launch'), ('earnings', 'Earnings/Financial'), ('policy_change', 'Policy Change'), ('incident', 'Incident/Crisis'), ('meeting', 'Meeting/Conference'), ('acquisition', 'Acquisition/Merger'), ('partnership', 'Partnership'), ('research', 'Research/Discovery'), ('legal', 'Legal/Court Decision'), ('election', 'Election/Political'), ('conflict', 'Conflict/War'), ('natural_disaster', 'Natural Disaster'), ('cultural', 'Cultural/Social'), ('sports', 'Sports Event'), ('other', 'Other')], default='other', help_text='Type of event for categorization', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='analyzer_ev_event_t_f855aa_idx'),
        ),
    ]
