# Generated by Django 5.0.2 on 2025-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_add_event_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('product_launch', 'Product Launch'), ('earnings', 'Earnings/Financial'), ('policy_change', 'Policy Change'), ('policy_debate', 'Policy Debate'), ('incident', 'Incident/Crisis'), ('meeting', 'Meeting/Conference'), ('acquisition', 'Acquisition/Merger'), ('partnership', 'Partnership'), ('research', 'Research/Discovery'), ('legal', 'Legal/Court Decision'), ('election', 'Election/Political'), ('conflict', 'Conflict/War'), ('natural_disaster', 'Natural Disaster'), ('cultural', 'Cultural/Social'), ('sports', 'Sports Event'), ('other', 'Other')], default='other', help_text='Type of event for categorization', max_length=20),
        ),
    ]
