# Generated by Django 5.0.2 on 2025-06-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_fix_articleevent_id_field'),
        ('articles', '0015_add_unique_content_hash'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articleevent',
            name='analyzer_article_event_is_primary_idx',
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_events', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Whether this is the primary/main event for the article'),
        ),
        migrations.AlterUniqueTogether(
            name='articleevent',
            unique_together={('article', 'event')},
        ),
    ]
