# Generated by Django 5.0.2 on 2025-06-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_remove_articleevent_analyzer_article_event_is_primary_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enhanced_abstract',
            field=models.TextField(blank=True, help_text='AI-enhanced comprehensive event summary from multiple articles'),
        ),
        migrations.AddField(
            model_name='event',
            name='enhanced_article_ids',
            field=models.JSONField(default=list, help_text='List of article IDs used for the last enhancement (for cache invalidation)'),
        ),
        migrations.AddField(
            model_name='event',
            name='enhanced_facts',
            field=models.JSONField(default=list, help_text='Enhanced key facts synthesized from multiple article perspectives'),
        ),
        migrations.AddField(
            model_name='event',
            name='enhanced_perspectives',
            field=models.JSONField(default=list, help_text='Different viewpoints and opinions about this event from various sources'),
        ),
        migrations.AddField(
            model_name='event',
            name='enhancement_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost of AI enhancement generation', max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='last_enhanced_at',
            field=models.DateTimeField(blank=True, help_text='When the enhanced summary was last generated', null=True),
        ),
    ]
