# Generated by Django 5.0.2 on 2025-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAPIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('top_headlines', 'Top Headlines'), ('everything', 'Everything'), ('sources', 'Sources')], max_length=20)),
                ('endpoint', models.CharField(max_length=255)),
                ('params', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('rate_limit_remaining', models.IntegerField(blank=True, null=True)),
                ('rate_limit_reset', models.DateTimeField(blank=True, null=True)),
                ('total_results', models.IntegerField(default=0)),
                ('results_fetched', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='newsapi_new_created_3b8594_idx'), models.Index(fields=['request_type'], name='newsapi_new_request_33aaa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsAPISyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('top_headlines', 'Top Headlines'), ('everything', 'Everything'), ('sources', 'Sources')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used for this sync')),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_created', models.IntegerField(default=0)),
                ('articles_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='newsapi_new_started_823b3e_idx'), models.Index(fields=['sync_type', 'status'], name='newsapi_new_sync_ty_adfe4c_idx')],
            },
        ),
    ]
