# Generated by Django 5.0.2 on 2025-05-07 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_storygroup_remove_article_news_api_id_and_more'),
        ('newsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAPIArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('newsapi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_top_headline', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsapi_data', to='articles.article')),
                ('sync_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsapi.newsapisynclog')),
            ],
            options={
                'verbose_name': 'NewsAPI Article',
                'verbose_name_plural': 'NewsAPI Articles',
                'indexes': [models.Index(fields=['source_id'], name='newsapi_new_source__c40c6f_idx'), models.Index(fields=['newsapi_id'], name='newsapi_new_newsapi_d4eb5d_idx'), models.Index(fields=['fetched_at'], name='newsapi_new_fetched_cfff02_idx')],
            },
        ),
    ]
