# Generated by Django 5.0.2 on 2025-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0002_newsapiarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapisynclog',
            name='sync_type',
            field=models.CharField(choices=[('top_headlines', 'Top Headlines'), ('everything', 'Everything'), ('sources', 'Sources'), ('everything_by_publication', 'Everything By Publication'), ('everything_by_sources_batched', 'Everything By Sources Batched')], max_length=50),
        ),
    ]
