# Generated by Django 5.0.2 on 2025-05-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0003_alter_newsapisynclog_sync_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapiarticle',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized domain name extracted from article URL', max_length=255, null=True),
        ),
    ]
