# Generated by Django 5.0.2 on 2025-04-30 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('news_api_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_top_headline', models.BooleanField(default=False)),
                ('summary_ready', models.BooleanField(default=False)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='feeds.language')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='feeds.publication')),
                ('regions', models.ManyToManyField(blank=True, related_name='articles', to='feeds.region')),
                ('topics', models.ManyToManyField(blank=True, related_name='articles', to='feeds.topic')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserArticleInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('bookmarked', models.BooleanField(default=False)),
                ('bookmarked_at', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='articles_ar_publish_c1a2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['public_id'], name='articles_ar_public__412f08_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['summary_ready'], name='articles_ar_summary_c060a9_idx'),
        ),
        migrations.AddIndex(
            model_name='userarticleinteraction',
            index=models.Index(fields=['user', 'read'], name='articles_us_user_id_911481_idx'),
        ),
        migrations.AddIndex(
            model_name='userarticleinteraction',
            index=models.Index(fields=['user', 'bookmarked'], name='articles_us_user_id_111c41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userarticleinteraction',
            unique_together={('user', 'article')},
        ),
    ]
