# Generated by Django 5.0.2 on 2025-05-07 00:51

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='news_api_id',
        ),
        migrations.AddField(
            model_name='article',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='article',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='articles.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='story_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.storygroup'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_top_headline'], name='articles_ar_is_top__b9e9be_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_hash'], name='articles_ar_content_432669_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['popularity_score'], name='articles_ar_popular_051be4_idx'),
        ),
    ]
