# Generated by Django 5.0.2 on 2025-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_allow_null_author'),
        ('feeds', '0002_publication_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_completeness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fetch_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='content_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_source',
            field=models.CharField(blank=True, choices=[('full_fetch', 'Full Content Fetched'), ('partial_fetch', 'Partial Content Fetched'), ('description', 'Using Description'), ('summary_only', 'Summary Only')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_status',
            field=models.CharField(choices=[('pending', 'Pending Fetch'), ('fetching', 'Fetching Content'), ('content_available', 'Full Content Available'), ('partial_content', 'Partial Content Available'), ('metadata_only', 'Metadata Only (No Content)'), ('paywall_blocked', 'Blocked by Paywall'), ('access_denied', 'Access Denied'), ('technical_error', 'Technical Error'), ('invalid_url', 'Invalid or Dead URL'), ('timeout', 'Request Timeout')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='fetch_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='last_fetch_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='last_processing_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='max_fetch_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='article',
            name='processing_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'AI Processing'), ('completed', 'Processing Completed'), ('failed', 'Processing Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='use_description_as_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_status'], name='articles_ar_content_41a83d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['processing_status'], name='articles_ar_process_17d8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_status', 'processing_status'], name='articles_ar_content_5ff00b_idx'),
        ),
    ]
