# Generated by Django 5.0.2 on 2025-05-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_content_completeness_and_more'),
        ('feeds', '0002_publication_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_structure',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='article',
            name='formatting_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='article',
            name='formatting_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='has_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='media_assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='media_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='rich_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['has_images'], name='articles_ar_has_ima_47bfea_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['has_videos'], name='articles_ar_has_vid_92e25f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['media_count'], name='articles_ar_media_c_979e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['formatting_score'], name='articles_ar_formatt_11a849_idx'),
        ),
    ]
