# Generated by Django 5.0.2 on 2025-05-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_add_rich_content_fields'),
    ]

    operations = [
    ]
