# Generated by Django 5.0.2 on 2025-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_step1_step2_refactor'),
        ('feeds', '0002_publication_domain'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_content_41a83d_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_process_17d8b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_content_5ff00b_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_formatt_11a849_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='basic_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='clean_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_quality_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='extracted_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='extraction_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='fetch_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='fetch_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='fetch_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='fetch_status',
            field=models.CharField(choices=[('pending', 'Pending Fetch'), ('fetching', 'Fetching Content'), ('completed', 'Fetch Completed'), ('failed', 'Fetch Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='fetch_strategy_used',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_process_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='paywall_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='paywall_indicators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='article',
            name='process_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='process_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='process_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='process_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='process_route',
            field=models.CharField(blank=True, choices=[('safari_mode', 'Safari Reader Mode'), ('llm_enhanced', 'LLM Enhanced'), ('hybrid', 'Hybrid Processing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='process_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing Content'), ('completed', 'Processing Completed'), ('failed', 'Processing Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='raw_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['fetch_status'], name='articles_ar_fetch_s_cfaa5d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['process_status'], name='articles_ar_process_8c7847_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['fetch_status', 'process_status'], name='articles_ar_fetch_s_fccbad_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['paywall_detected'], name='articles_ar_paywall_6ff959_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['process_route'], name='articles_ar_process_d31ae5_idx'),
        ),
    ]
