# Generated by Django 5.0.2 on 2025-06-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_articles_ar_content_41a83d_idx_and_more'),
        ('feeds', '0002_publication_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_summarization_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summarization_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='summarization_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summarization_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summarization_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summarization_status',
            field=models.CharField(choices=[('pending', 'Pending Summarization'), ('processing', 'Processing Summary'), ('completed', 'Summary Completed'), ('failed', 'Summary Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='summarized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_content_source',
            field=models.CharField(blank=True, choices=[('imcomplete_text', 'Imcomplete Text'), ('full_cleaned_text', 'Full Cleaned Text'), ('rich_content_blocks', 'Rich Content Blocks')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['summarization_status'], name='articles_ar_summari_dc45de_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['summarized_at'], name='articles_ar_summari_a3b84e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['summary_content_source'], name='articles_ar_summary_b17e52_idx'),
        ),
    ]
