# Generated by Django 5.0.2 on 2025-06-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_last_summarization_attempt_and_more'),
        ('feeds', '0002_publication_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='analyzer_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='analyzer_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='analyzer_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='analyzer_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='analyzer_status',
            field=models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing Analysis'), ('completed', 'Analysis Completed'), ('failed', 'Analysis Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='last_analyzer_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='primary_region',
            field=models.ForeignKey(blank=True, help_text='Primary region as determined by analyzer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='feeds.region'),
        ),
        migrations.AddField(
            model_name='article',
            name='primary_topic',
            field=models.ForeignKey(blank=True, help_text='Primary topic as determined by analyzer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='feeds.topic'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['analyzer_status'], name='articles_ar_analyze_e48ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['analyzed_at'], name='articles_ar_analyze_31b3aa_idx'),
        ),
    ]
