# Generated by Django 5.0.2 on 2025-06-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_analyzed_at_article_analyzer_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readability_score',
            field=models.FloatField(blank=True, help_text='Flesch readability score (0-100, higher = easier)', null=True),
        ),
    ]
