# Generated by Django 5.0.2 on 2025-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_add_readability_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
