# Generated by Django 5.0.2 on 2026-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_add_rss_direct_process_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='triage_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='triage_method',
            field=models.CharField(blank=True, choices=[('algorithmic', 'Algorithmic'), ('llm', 'LLM'), ('cluster_promotion', 'Cluster Promotion'), ('legacy', 'Legacy')], max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='triage_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='triage_score',
            field=models.FloatField(blank=True, help_text='Composite triage score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='triage_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_llm', 'Pending LLM'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('promoted', 'Promoted')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
