# Generated by Django 5.0.2 on 2025-06-11 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0012_article_last_summarization_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for aggregated metrics', unique=True)),
                ('articles_processed', models.IntegerField(default=0)),
                ('articles_failed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate percentage')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('avg_cost_per_article', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('avg_duration_ms', models.IntegerField(default=0)),
                ('avg_tokens_used', models.IntegerField(default=0)),
                ('critic_trigger_rate', models.FloatField(default=0.0, help_text='Percentage triggering critic review')),
                ('repair_rate', models.FloatField(default=0.0, help_text='Percentage requiring repair')),
                ('rbc_failures', models.IntegerField(default=0)),
                ('summary_failures', models.IntegerField(default=0)),
                ('critic_failures', models.IntegerField(default=0)),
                ('embedding_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_summarization_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('embedding', models.JSONField(help_text='1536-dimensional vector as JSON array')),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=50)),
                ('embedding_text', models.TextField(help_text='Text used for embedding generation')),
                ('embedding_length', models.IntegerField(help_text='Vector dimension count')),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='articles.article')),
            ],
            options={
                'db_table': 'content_article_embedding',
                'indexes': [models.Index(fields=['article'], name='content_art_article_0a7831_idx'), models.Index(fields=['embedding_model'], name='content_art_embeddi_45b795_idx'), models.Index(fields=['created_at'], name='content_art_created_581a42_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleRBC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bullets', models.JSONField(help_text='List of labeled bullet points')),
                ('rbc_version', models.SmallIntegerField(default=1)),
                ('bullet_count', models.IntegerField(help_text='Number of bullets generated')),
                ('content_source', models.CharField(choices=[('imcomplete_text', 'Imcomplete Text'), ('full_cleaned_text', 'Full Cleaned Text'), ('rich_content_blocks', 'Rich Content Blocks')], help_text='Source content used for RBC', max_length=20)),
                ('original_content_length', models.IntegerField(help_text='Original content character count')),
                ('truncated_at', models.IntegerField(blank=True, help_text='Character position where content was truncated', null=True)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('ai_model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rbc', to='articles.article')),
            ],
            options={
                'db_table': 'content_article_rbc',
                'indexes': [models.Index(fields=['article'], name='content_art_article_fe70c8_idx'), models.Index(fields=['content_source'], name='content_art_content_82bc72_idx'), models.Index(fields=['created_at'], name='content_art_created_6ea358_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('headline', models.CharField(help_text='≤15 words', max_length=255)),
                ('abstract', models.TextField(help_text='≤60 words, neutral tone')),
                ('facts', models.JSONField(default=list, help_text='3-6 key facts verbatim from RBC')),
                ('opinions', models.JSONField(default=list, help_text='Speaker: opinion pairs')),
                ('impact', models.JSONField(default=list, help_text='≤3 impact bullets prefixed with ⚡')),
                ('summary_version', models.SmallIntegerField(default=2)),
                ('content_source', models.CharField(help_text='Source used for summarization', max_length=20)),
                ('headline_words', models.IntegerField(help_text='Headline word count')),
                ('abstract_words', models.IntegerField(help_text='Abstract word count')),
                ('facts_count', models.IntegerField(help_text='Number of facts')),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('ai_model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('required_critic_review', models.BooleanField(default=False, help_text='Whether critic review was triggered')),
                ('critic_passed', models.BooleanField(blank=True, help_text='Result of critic review', null=True)),
                ('was_repaired', models.BooleanField(default=False, help_text='Whether summary was repaired after critic')),
                ('repair_attempts', models.IntegerField(default=0, help_text='Number of repair attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_summary', to='articles.article')),
            ],
            options={
                'db_table': 'content_article_summary',
                'indexes': [models.Index(fields=['article'], name='content_art_article_5eea33_idx'), models.Index(fields=['summary_version'], name='content_art_summary_8f472f_idx'), models.Index(fields=['required_critic_review'], name='content_art_require_ef1540_idx'), models.Index(fields=['was_repaired'], name='content_art_was_rep_05f26c_idx'), models.Index(fields=['created_at'], name='content_art_created_f090c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SummarizationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rbc_processing', 'RBC Processing'), ('summary_processing', 'Summary Processing'), ('critic_processing', 'Critic Processing'), ('repair_processing', 'Repair Processing'), ('embedding_processing', 'Embedding Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('current_stage', models.CharField(blank=True, help_text='Current processing stage', max_length=20)),
                ('stages_completed', models.JSONField(default=list, help_text='List of completed stages')),
                ('pipeline_start_time', models.DateTimeField(blank=True, null=True)),
                ('pipeline_end_time', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('failed_stage', models.CharField(blank=True, max_length=20)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('total_duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarization_requests', to='articles.article')),
            ],
            options={
                'db_table': 'content_summarization_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='content_sum_status_7fccb0_idx'), models.Index(fields=['article', 'status'], name='content_sum_article_d1294b_idx'), models.Index(fields=['current_stage'], name='content_sum_current_2928e3_idx'), models.Index(fields=['created_at'], name='content_sum_created_c63e22_idx')],
            },
        ),
    ]
