# Generated by Django 5.0.2 on 2025-06-12 15:40

import pgvector.django
from django.db import migrations, models
import json


def convert_json_to_vector(apps, schema_editor):
    """Convert existing JSON embeddings to vector format"""
    
    # Raw SQL to safely convert jsonb to vector
    schema_editor.execute("""
        -- Add temporary vector column
        ALTER TABLE content_article_embedding 
        ADD COLUMN embedding_vector vector(1536);
    """)
    
    # Convert data from jsonb array to vector
    schema_editor.execute("""
        UPDATE content_article_embedding 
        SET embedding_vector = embedding::text::vector(1536)
        WHERE embedding IS NOT NULL;
    """)
    
    # Drop old jsonb column
    schema_editor.execute("""
        ALTER TABLE content_article_embedding 
        DROP COLUMN embedding;
    """)
    
    # Rename vector column to embedding
    schema_editor.execute("""
        ALTER TABLE content_article_embedding 
        RENAME COLUMN embedding_vector TO embedding;
    """)
    
    # Make it NOT NULL
    schema_editor.execute("""
        ALTER TABLE content_article_embedding 
        ALTER COLUMN embedding SET NOT NULL;
    """)


def reverse_vector_to_json(apps, schema_editor):
    """Reverse conversion from vector to jsonb format"""
    
    # Add temporary jsonb column
    schema_editor.execute("""
        ALTER TABLE content_article_embedding 
        ADD COLUMN embedding_jsonb jsonb;
    """)
    
    # Convert vector to jsonb array
    schema_editor.execute("""
        UPDATE content_article_embedding 
        SET embedding_jsonb = to_jsonb(embedding::real[])
        WHERE embedding IS NOT NULL;
    """)
    
    # Drop vector column
    schema_editor.execute("""
        ALTER TABLE content_article_embedding 
        DROP COLUMN embedding;
    """)
    
    # Rename jsonb column back
    schema_editor.execute("""
        ALTER TABLE content_article_embedding 
        RENAME COLUMN embedding_jsonb TO embedding;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('summariser', '0002_enable_pgvector'),
    ]

    operations = [
        # Convert the embedding field from jsonb to vector
        migrations.RunPython(convert_json_to_vector, reverse_vector_to_json),
        
        # Update the Django model definition to match
        migrations.AlterField(
            model_name='articleembedding',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536, help_text='1536-dimensional vector using pgvector'),
        ),
    ] 