# Generated by Django 5.0.2 on 2025-06-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summariser', '0003_convert_embeddings_to_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesummary',
            name='longer_abstract',
            field=models.TextField(blank=True, help_text='≤200 words, comprehensive compression', null=True),
        ),
        migrations.AddField(
            model_name='articlesummary',
            name='longer_abstract_words',
            field=models.IntegerField(blank=True, help_text='Longer abstract word count', null=True),
        ),
        migrations.AlterField(
            model_name='articlesummary',
            name='impact',
            field=models.JSONField(default=list, help_text='≤3 impact bullets'),
        ),
    ]
