# Generated by Django 5.0.2 on 2025-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='digest_preferences',
            field=models.JSONField(default=dict, help_text='Digest customization preferences including max topics, events per topic, delivery time, etc.'),
        ),
    ]
