# Generated by Django 5.0.2 on 2025-05-30 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0011_remove_article_articles_ar_content_41a83d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityScoring',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('overall_score', models.DecimalField(decimal_places=3, help_text='Overall quality score (-1 to 1)', max_digits=4)),
                ('completeness_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('purity_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('structure_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('readability_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('assessment_method', models.CharField(choices=[('pre_filter', 'Pre-filter Assessment'), ('llm_evaluation', 'LLM Evaluation'), ('error_fallback', 'Error Fallback'), ('batch_error', 'Batch Error')], help_text='Method used for assessment', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=3, help_text='Confidence in assessment', max_digits=4)),
                ('processing_time_ms', models.IntegerField(help_text='Processing time in milliseconds')),
                ('cost_optimized', models.BooleanField(default=False, help_text='Whether cost was optimized via pre-filter')),
                ('detailed_feedback', models.TextField(blank=True, help_text='Detailed feedback from LLM', null=True)),
                ('identified_issues', models.JSONField(blank=True, help_text='List of identified issues', null=True)),
                ('pre_filter_reason', models.CharField(blank=True, help_text='Pre-filter decision reason', max_length=100, null=True)),
                ('pre_filter_issues', models.JSONField(blank=True, help_text='Issues detected by pre-filter', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to='articles.article')),
            ],
            options={
                'db_table': 'content_quality_scoring',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article'], name='content_qua_article_2ec90c_idx'), models.Index(fields=['overall_score'], name='content_qua_overall_62038b_idx'), models.Index(fields=['assessment_method'], name='content_qua_assessm_f81d43_idx'), models.Index(fields=['created_at'], name='content_qua_created_906fca_idx')],
            },
        ),
    ]
