# Generated by Django 5.0.2 on 2025-06-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptComparisonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Test experiment name', max_length=100)),
                ('description', models.TextField(help_text="Description of what's being tested")),
                ('baseline_template_id', models.CharField(help_text="Baseline template identifier (e.g., 'quality_evaluation_v1.0')", max_length=100)),
                ('variant_template_id', models.CharField(help_text="Variant template identifier (e.g., 'quality_evaluation_v1.1-concise')", max_length=100)),
                ('sample_size', models.IntegerField(help_text='Number of articles to test on')),
                ('content_type', models.CharField(choices=[('clean', 'Clean'), ('basic', 'Basic'), ('raw', 'Raw'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('baseline_avg_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('variant_avg_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('baseline_avg_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('variant_avg_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('baseline_avg_tokens', models.IntegerField(blank=True, null=True)),
                ('variant_avg_tokens', models.IntegerField(blank=True, null=True)),
                ('score_improvement', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('cost_change', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('is_significant', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='qualityscoring',
            name='template_used',
            field=models.CharField(blank=True, help_text="Template identifier used (e.g., 'quality_evaluation_v1.1-concise')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qualityscoring',
            name='template_version',
            field=models.CharField(blank=True, help_text="Template version used (e.g., 'v1.1-concise')", max_length=50, null=True),
        ),
    ]
