# Generated by Django 5.0.2 on 2025-06-02 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_articles_ar_content_41a83d_idx_and_more'),
        ('quality', '0002_promptcomparisontest_qualityscoring_template_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceQualityExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quality_class', models.CharField(choices=[('perfect', 'Perfect (>0.95)'), ('good', 'Good (0.80-0.95)'), ('imperfect', 'Imperfect (0.00-0.80)'), ('awful', 'Awful (<0.00)')], help_text='Reference quality classification', max_length=20)),
                ('reference_overall_score', models.FloatField(help_text='Reference overall quality score (-1.0 to 1.0)')),
                ('reference_completeness', models.FloatField(help_text='Reference completeness score (0.0 to 1.0)')),
                ('reference_purity', models.FloatField(help_text='Reference purity score (0.0 to 1.0)')),
                ('reference_structure', models.FloatField(help_text='Reference structure score (0.0 to 1.0)')),
                ('reference_readability', models.FloatField(help_text='Reference readability score (0.0 to 1.0)')),
                ('reference_explanation', models.TextField(help_text='Detailed explanation of quality assessment')),
                ('reference_missing_elements', models.JSONField(default=list, help_text='List of missing elements')),
                ('reference_noise_detected', models.JSONField(default=list, help_text='List of noise types detected')),
                ('reference_key_strengths', models.JSONField(default=list, help_text='List of extraction strengths')),
                ('reference_improvement_areas', models.JSONField(default=list, help_text='List of improvement areas')),
                ('stored_raw_html', models.TextField(blank=True, help_text='Stored raw HTML for reference')),
                ('stored_preprocessed_html', models.TextField(blank=True, help_text='Stored preprocessed HTML for reference')),
                ('stored_extracted_content', models.TextField(blank=True, help_text='Stored extracted content for reference')),
                ('stored_content_blocks', models.JSONField(default=list, help_text='Stored content blocks for reference')),
                ('use_in_prompts', models.BooleanField(default=True, help_text='Include in few-shot prompt examples')),
                ('use_for_calibration', models.BooleanField(default=True, help_text='Use for evaluation calibration')),
                ('use_for_benchmarking', models.BooleanField(default=True, help_text='Use for extraction pipeline benchmarking')),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this example')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_quality_examples', to='articles.article')),
            ],
            options={
                'db_table': 'quality_reference_examples',
                'ordering': ['quality_class', '-reference_overall_score'],
                'indexes': [models.Index(fields=['quality_class'], name='quality_ref_quality_59108b_idx'), models.Index(fields=['use_in_prompts'], name='quality_ref_use_in__36fd7a_idx'), models.Index(fields=['use_for_calibration'], name='quality_ref_use_for_6341aa_idx')],
            },
        ),
    ]
