"""
Django settings for dailybrief project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Set a safer recursion limit
sys.setrecursionlimit(1000)  # Default is 1000, set to a conservative value

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ul2m53&s_0=7rm3e+xeb3c6b4oopc%=860)t@z(pgwo-$7-^j(')

# SECURITY WARNING: don't run with debug turned on in production!
# Force DEBUG to False to avoid recursive errors
DEBUG = False

ALLOWED_HOSTS = ['*']  # Allow all hosts for now

# Detailed logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  # Add DRF authtoken app for Token model
    'corsheaders',
    
    # Local apps
    'apps.core',  # Core utilities
    'apps.accounts',
    'apps.feeds',
    'apps.articles',
    'apps.newsapi',
    'apps.aiproviders',
    'apps.notifications',
    
    # Content Domain
    'apps.content',  # Main content package
    'apps.content.fetcher',
    'apps.content.processor',
    'apps.content.quality',
    'apps.content.summariser',
    'apps.content.analyzer',
    'apps.content.digest',  # Digest generation
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.accounts.middleware.JWTAuthenticationMiddleware',  # JWT auth middleware
]

# CORS configuration
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'dailybrief.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dailybrief.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('SUPABASE_DB_NAME', 'postgres'),
        'USER': os.getenv('SUPABASE_DB_USER', 'postgres'),
        'PASSWORD': os.getenv('SUPABASE_DB_PASSWORD', ''),
        'HOST': os.getenv('SUPABASE_DB_HOST', 'localhost'),
        'PORT': os.getenv('SUPABASE_DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.accounts.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Task timeout settings to prevent stuck tasks
CELERY_TASK_SOFT_TIME_LIMIT = 600  # 10 minutes soft limit
CELERY_TASK_TIME_LIMIT = 900       # 15 minutes hard limit
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Don't prefetch too many tasks

# Celery Beat Schedule
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Top Headlines - Twice daily at 4am and 2pm
    'sync-top-headlines-morning': {
        'task': 'newsapi.sync_headlines',
        'schedule': crontab(hour=4, minute=0),  # 4:00 AM
    },
    'sync-top-headlines-afternoon': {
        'task': 'newsapi.sync_headlines',
        'schedule': crontab(hour=14, minute=0),  # 2:00 PM
    },
    
    # Recent Articles by Sources - Once per day at 4am to get previous day's news
    'sync-recent-by-sources-daily': {
        'task': 'newsapi.sync_recent_by_sources',
        'schedule': crontab(hour=4, minute=0),  # 4:00 AM
        'kwargs': {'hours': 24, 'batch_size': 20},
    },
    
    # Sources update - Weekly on Sunday at 3:00 AM
    'sync-sources-weekly': {
        'task': 'newsapi.sync_sources',
        'schedule': crontab(hour=3, minute=0, day_of_week=0),  # Sunday at 3:00 AM
        'kwargs': {'update_existing': True},
    },
    
    # Content Fetching Tasks - DISABLED: Use content-enrichment pipeline only for complete control
    # Process pending articles for content fetching - Every 15 minutes (increased frequency)
    # 'process-pending-articles': {
    #     'task': 'apps.content.fetcher.tasks.fetch_pending_articles',  # Fixed: was 'content.process_pending_articles'
    #     'schedule': crontab(minute='*/15'),  # Every 15 minutes (was 30)
    #     'kwargs': {'limit': 100},  # Increased from 50
    # },
    
    # Retry failed content fetches - Every hour (increased frequency)
    # 'retry-failed-fetches': {
    #     'task': 'apps.content.fetcher.tasks.retry_failed_fetches',  # Fixed: was 'content.retry_failed_fetches'
    #     'schedule': crontab(minute=0),  # Every hour
    #     'kwargs': {'limit': 50},
    # },
    
    # Update content metrics - Daily at 6:00 AM
    'update-content-metrics': {
        'task': 'apps.content.fetcher.tasks.get_fetch_statistics',  # Fixed: was 'content.update_content_metrics'
        'schedule': crontab(hour=6, minute=0),  # 6:00 AM daily
    },
    
    # Cleanup old fetch logs - Weekly on Monday at 2:00 AM
    'cleanup-old-fetch-logs': {
        'task': 'apps.content.fetcher.tasks.cleanup_old_fetch_attempts',  # Fixed: was 'content.cleanup_old_fetch_logs'
        'schedule': crontab(hour=2, minute=0, day_of_week=1),  # Monday at 2:00 AM
        'kwargs': {'days_to_keep': 30},
    },
    
    # CONTENT ENRICHMENT PIPELINE - PRODUCTION SCHEDULE
    # Distributed throughout the day for optimal processing
    'content-enrichment-morning': {
        'task': 'apps.content.tasks.process_top_headlines_pipeline',  # Fixed: was 'content.process_top_headlines_pipeline'
        'schedule': crontab(hour=4, minute=0),  # 4:00 AM UTC
        'kwargs': {'limit': 80},  # Increased from 50
    },
    
    'content-enrichment-afternoon': {
        'task': 'apps.content.tasks.process_top_headlines_pipeline',  # Fixed: was 'content.process_top_headlines_pipeline'
        'schedule': crontab(hour=14, minute=0),  # 2:00 PM UTC (afternoon)
        'kwargs': {'limit': 80},  # Increased from 50
    },
    
    'content-enrichment-followup-morning': {
        'task': 'apps.content.tasks.process_top_headlines_pipeline',  # Fixed: was 'content.process_top_headlines_pipeline'
        'schedule': crontab(hour=5, minute=0),  # 5:00 AM UTC (followup morning)
        'kwargs': {'limit': 80},  # Increased from 30
    },
    
    'content-enrichment-followup-afternoon': {
        'task': 'apps.content.tasks.process_top_headlines_pipeline',  # Fixed: was 'content.process_top_headlines_pipeline'
        'schedule': crontab(hour=15, minute=0),  # 3:00 PM UTC (followup afternoon)
        'kwargs': {'limit': 80},  # Increased from 30
    },
    
    'content-enrichment-evening': {
        'task': 'apps.content.tasks.process_top_headlines_pipeline',
        'schedule': crontab(hour=20, minute=0),  # 8:00 PM UTC (evening)
        'kwargs': {'limit': 100},  # Higher limit for peak day handling
    },
    
    'content-enrichment-late-evening': {
        'task': 'apps.content.tasks.process_top_headlines_pipeline', 
        'schedule': crontab(hour=21, minute=0),  # 11:00 PM UTC (late evening)
        'kwargs': {'limit': 100},  # Higher limit for peak day handling
    },
    
    # Pipeline maintenance and monitoring tasks
    
    # Clean up failed articles that exceeded max retries - Daily at 1:00 AM
    'cleanup-failed-pipeline-articles': {
        'task': 'apps.content.tasks.cleanup_failed_pipeline_articles',  # Fixed: was 'content.cleanup_failed_pipeline_articles'
        'schedule': crontab(hour=1, minute=0),  # 1:00 AM daily
        'kwargs': {'max_attempts': 3},
    },
    
    # Retry previously failed articles - Every 3 hours (increased frequency)
    'retry-failed-pipeline-stages': {
        'task': 'apps.content.tasks.retry_failed_pipeline_stages',  # Fixed: was 'content.retry_failed_pipeline_stages'
        'schedule': crontab(minute=0, hour='*/3'),  # Every 3 hours (was 6)
        'kwargs': {'stage': 'all', 'limit': 50},  # Increased from 20
    },
    
    # Pipeline status monitoring - Every 2 hours for debugging
    'pipeline-status-check': {
        'task': 'apps.content.tasks.get_pipeline_status',  # Fixed: was 'content.get_pipeline_status'
        'schedule': crontab(minute=30, hour='*/2'),  # Every 2 hours at :30
    },
    
    # ===== DIGEST GENERATION TASKS =====
    # Generate daily digests at 6:00 AM UTC after content enrichment completes
    'generate-daily-digests': {
        'task': 'apps.content.digest.tasks.generate_daily_digests_for_all_users',
        'schedule': crontab(hour=6, minute=0),  # 6:00 AM UTC (1 hour after content enrichment starts)
        'kwargs': {'force_regenerate': False},
    },
    
    # Regenerate failed digests at 7:00 AM UTC
    'regenerate-failed-digests': {
        'task': 'apps.content.digest.tasks.regenerate_failed_digests',
        'schedule': crontab(hour=7, minute=0),  # 7:00 AM UTC (1 hour after content enrichment starts)
    },
    
    # Cleanup old digests - Weekly on Sunday at 1:00 AM
    'cleanup-old-digests': {
        'task': 'apps.content.digest.tasks.cleanup_old_digests',
        'schedule': crontab(hour=1, minute=0, day_of_week=0),  # Sunday at 1:00 AM
        'kwargs': {'days_to_keep': 90},
    },
    
    # ===== STUCK ARTICLE CLEANUP TASKS =====
    # Clean up articles stuck in processing status - Every hour
    'cleanup-stuck-processing-articles': {
        'task': 'apps.content.processor.tasks.cleanup_processing_data',
        'schedule': crontab(minute=15, hour='*'),  # Every hour at :15
    },
    
    # Clean up articles stuck in fetching status - Every hour
    'cleanup-stuck-fetching-articles': {
        'task': 'apps.content.fetcher.tasks.cleanup_old_fetch_attempts',
        'schedule': crontab(minute=45, hour='*'),  # Every hour at :45
    },
    
    # Clean up articles stuck in summarization status - Every hour
    'cleanup-stuck-summarization-articles': {
        'task': 'apps.content.summariser.tasks.cleanup_stuck_summarization_articles',
        'schedule': crontab(minute=25, hour='*'),  # Every hour at :25
    },
    
    # Clean up articles stuck in analysis status - Every hour
    'cleanup-stuck-analyzer-articles': {
        'task': 'apps.content.analyzer.tasks.cleanup_stuck_analyzer_articles',
        'schedule': crontab(minute=35, hour='*'),  # Every hour at :35
    },
}

# News API
NEWSAPI_API_KEY = os.getenv('NEWS_API_KEY', '')

# AI Providers
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')

# AI Rate Limiting Configuration
# Updated for 2M TPM limit (10x increase from 200k TPM)
# With content extraction averaging ~20k tokens per call
AI_RATE_LIMIT_CALLS_PER_MINUTE = int(os.getenv('AI_RATE_LIMIT_CALLS_PER_MINUTE', '150'))  # Increased from 80 to 150 (~2.7M tokens/min, 90% of limit)
AI_RATE_LIMIT_BURST_CAPACITY = int(os.getenv('AI_RATE_LIMIT_BURST_CAPACITY', '50'))  # Increased burst capacity for parallel processing

# Digest Generation Configuration
DIGEST_BATCH_SIZE = int(os.getenv('DIGEST_BATCH_SIZE', '50'))  # Users processed per batch
DIGEST_DEFAULT_TIMEZONE = os.getenv('DIGEST_DEFAULT_TIMEZONE', 'UTC')  # Default user timezone
DIGEST_MAX_COST_PER_USER = float(os.getenv('DIGEST_MAX_COST_PER_USER', '0.50'))  # Max AI cost per user digest
