# Generated by Django 5.0.2 on 2025-05-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized domain name (e.g., nytimes.com)', max_length=255, null=True),
        ),
    ]
