# Generated by Django 5.0.2 on 2025-06-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_publication_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, help_text='Description to help AI models with classification'),
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, help_text='Description to help AI models with classification'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, help_text='Description to help AI models with classification'),
        ),
    ]
