# Generated by Django 5.0.2 on 2025-04-30 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(help_text='Date this digest covers')),
                ('introduction', models.TextField(help_text="AI-generated introduction to the day's stories")),
                ('html_content', models.TextField(help_text='Full HTML content of the digest')),
                ('is_published', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DigestStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(related_name='digest_stories', to='articles.article')),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='digest.digest')),
            ],
            options={
                'verbose_name_plural': 'Digest stories',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['-date'], name='digest_dige_date_bb3ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['public_id'], name='digest_dige_public__dfe3c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='digest',
            unique_together={('user', 'date')},
        ),
    ]
