# Generated by Django 5.0.2 on 2025-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('summarization', 'Article Summarization'), ('digest_generation', 'Digest Generation'), ('translation', 'Translation')], max_length=20, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('other', 'Other Provider')], max_length=20)),
                ('model', models.CharField(help_text='Specific model to use', max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Provider-specific configuration options')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIProviderUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('other', 'Other Provider')], max_length=20)),
                ('model', models.CharField(help_text="Specific model used (e.g. 'gpt-3.5-turbo')", max_length=50)),
                ('operation', models.CharField(choices=[('summarization', 'Article Summarization'), ('digest_generation', 'Digest Generation'), ('translation', 'Translation')], max_length=20)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_time', models.FloatField(default=0, help_text='Response time in seconds')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI provider usages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='aiproviders_created_34f841_idx'), models.Index(fields=['provider', 'operation'], name='aiproviders_provide_b0af06_idx')],
            },
        ),
    ]
