# Generated by Django 5.0.2 on 2025-05-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproviders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='operation',
            field=models.CharField(choices=[('summarization', 'Article Summarization'), ('digest_generation', 'Digest Generation'), ('translation', 'Translation'), ('quality_assessment', 'Content Quality Assessment')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='aiproviderusage',
            name='operation',
            field=models.CharField(choices=[('summarization', 'Article Summarization'), ('digest_generation', 'Digest Generation'), ('translation', 'Translation'), ('quality_assessment', 'Content Quality Assessment')], max_length=30),
        ),
    ]
