# Generated by Django 5.0.2 on 2025-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproviders', '0004_add_summarization_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='operation',
            field=models.CharField(choices=[('summarization', 'Article Summarization'), ('digest_generation', 'Digest Generation'), ('translation', 'Translation'), ('quality_assessment', 'Content Quality Assessment'), ('content_extraction', 'Content Extraction'), ('rbc_compression', 'Rich Bullet Compression'), ('skeleton_summary', 'Skeleton Summary Generation'), ('summary_critique', 'Summary Critique Review'), ('summary_repair', 'Summary Repair'), ('embedding_generation', 'Embedding Generation'), ('linguistic_analysis', 'Linguistic Analysis'), ('entity_extraction', 'Entity Extraction'), ('event_detection', 'Event Detection'), ('topic_classification', 'Topic Classification'), ('region_classification', 'Region Classification')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='aiproviderusage',
            name='operation',
            field=models.CharField(choices=[('summarization', 'Article Summarization'), ('digest_generation', 'Digest Generation'), ('translation', 'Translation'), ('quality_assessment', 'Content Quality Assessment'), ('content_extraction', 'Content Extraction'), ('rbc_compression', 'Rich Bullet Compression'), ('skeleton_summary', 'Skeleton Summary Generation'), ('summary_critique', 'Summary Critique Review'), ('summary_repair', 'Summary Repair'), ('embedding_generation', 'Embedding Generation'), ('linguistic_analysis', 'Linguistic Analysis'), ('entity_extraction', 'Entity Extraction'), ('event_detection', 'Event Detection'), ('topic_classification', 'Topic Classification'), ('region_classification', 'Region Classification')], max_length=30),
        ),
    ]
